name: Test CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    test:
        name: Rust Test
        runs-on: ubuntu-latest
        steps:
            - run: sudo su
            - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
            - run: apt-get -y update && apt-get -y install libpcap-dev telnet
            - uses: actions/checkout@v2
            - run: ~/.cargo/bin/cargo test
