name: Test CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    test:
        name: Rust Test
        runs-on: ubuntu-latest
        steps:
            - name: Use Docker in rootless mode.
              uses: ScribeMD/rootless-docker@0.1.2
            - uses: actions/checkout@v2
            - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
            - run: apt-get -y update && apt-get -y install libpcap-dev telnet
            - uses: actions/checkout@v2
            - run: ~/.cargo/bin/cargo test
