name: Test CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    test:
        name: Rust Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - run: sudo apt-get -y update && sudo apt-get -y install libpcap-dev telnet
            - run: cargo test
