name: Test CI

on:
    push:
        branches: [main]
        paths-ignore:
            - '**/*.md'
            - LICENSE
            - '**/*.gitignore'
            - examples/**
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    test:
        name: Rust Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - run: curl https://sh.rustup.rs -sSf | sudo sh -s -- -y
            - run: sudo apt-get -y update && sudo apt-get -y install libpcap-dev telnet
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - run: sudo ~/.cargo/bin/cargo test
